name: Run All Tests 
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Checkout
      uses: actions/checkout@v2

    - name: Checkout tidb-server@master
      uses: actions/checkout@master
      with:
        repository: pingcap/tidb
        path: tidb

    - name: Build tidb-server@master
      run: |
        # This can be cached in the future
        # But as long as it doesn't consume too much time, it's simple to build
        cd tidb
        make server
        cd ..

    - name: Run tests 
      run: |
        # There is no -t all, so for now I'm using record mode and checking for diffs.
        # This should be fixed in future, since there are some legal differences.
        # that are stabalized with macros.
        ./run-tests.sh -s ./tidb/bin/tidb-server -r all
        # Exit if there are any changes 
        if [[ $(git diff) ]]; then
         echo "git diff shows changes:";
         git diff
         exit 1
        else
         echo "no changes";
        fi